packages/select-field/SelectField.tsx

onChange should receive an argument (in case event)

fix(select-field): change type of onChange function

---

package.json
packages/table/Table.tsx
packages/table/package.json

Table size was fixed at 60%, it can be, but needs to accpet an optional width.

Fix: Updated Table to accept optional width

---

packages/table/Table.tsx

It must accept in order to deal with fluid layouts.

feat: added optional heigth to table

---

packages/button/package.json
packages/checkbox/package.json
packages/core/package.json
packages/form-buttons/package.json
packages/form-section/package.json
packages/form/package.json
packages/loader/package.json
packages/pismo-id/package.json
packages/search-field/package.json
packages/search-list/package.json
packages/select-field/package.json
packages/table-item/package.json
packages/table/Table.test.tsx
packages/table/package.json
packages/text-field/package.json
packages/timer/package.json
packages/toast/package.json
packages/uploader/package.json

test: new test added to release

---

tsconfig.json

fix: node_modules check

---

packages/form-control/FormControl.tsx

disparo de evento para manipulação de erro

feat: (FormControl) error event

---

lerna.json
packages/world-format/WorldFormat.ts

implementação para adicionar a lista de estado e municípios na localStorage

feat: (WorldFormat) state & cities localStorage

---

packages/calendar/Calendar.tsx
packages/calendar/components/DaysContainer.tsx
packages/calendar/index.ts

feat (Calendar): expose utils functions

---

packages/world-format/WorldFormat.ts
packages/world-format/package.json

fix (WorldFormat): fetch don't work on Cypress

---

packages/percentage-input/PercentInput.tsx

fix: correcao deletar numero

---

packages/calendar/Calendar.tsx
packages/calendar/components/DaysContainer.tsx
packages/calendar/components/FirstHeader.tsx
packages/calendar/index.ts
packages/calendar/package.json

feat (Calendar): added new features to Calendar

---

packages/core/themes/PismoCleanTheme.ts
packages/core/themes/PismoDarkTheme.ts

referente à: https://pismolabs.atlassian.net/browse/PISMO-7987
para testar:
Dentro do monopoly, faça checkout nesta branch no bolt e faça o build. Em seguida rode o marketplace

feat: text field theme changed with background

---

.github/CODEOWNERS
packages/calendar/components/DaysContainer.tsx
packages/core/themes/PismoCleanTheme.ts
packages/pismo-bar/PismoBar.tsx
packages/pismo-bar/components/ApplicationToolbar.tsx
packages/pismo-user-bar/PismoUserBar.tsx
packages/pismo-user-bar/components/ApplicationToolbar.tsx
yarn.lock

Fix: new bgcolor in PismoBar and PismoUserBar

---

packages/pismo-bar/PismoBar.tsx

referente à: https://pismolabs.atlassian.net/browse/PISMO-8298
Botão para fechar a PismoBar adicionado para melhorar a experiência do usuário

feat(PismoBar): close button added

---

packages/calendar/Calendar.mdx
packages/calendar/Calendar.tsx
packages/calendar/components/DaysContainer.tsx
packages/calendar/components/MonthContainer.tsx
packages/calendar/components/RangeBarButton.tsx
packages/calendar/components/SwitchBar.tsx
packages/calendar/components/YearContainer.tsx

referente à : https://pismolabs.atlassian.net/browse/PISMO-8297

feat: Calendar features

---

packages/pismo-bar/PismoBar.tsx

New bg color in close button container

---

src/icons/icons.css
src/icons/icons.mdx

docs(icons): documentation improvements

---

packages/pismo-bar/PismoBar.mdx
packages/pismo-bar/PismoBar.tsx
packages/pismo-bar/components/ApplicationToolbar.tsx
packages/pismo-bar/components/interfaces.ts

TESTS
**-**
**-**
**-**
**-**
**-**
**-**
I18N
**-**
MULTICURRENCY
**-**

feat: adding parameter activation link

---

package.json
src/bolt-css.css
src/colors/colors.css
src/scroll-bar/scroll-bar.css

- adicionado variaveis globais para as cores do tema
- adicionada scrollbar na cor clara

feat: color variables

---

src/button/button.css
src/button/button.mdx

feat(button): new kinds of buttons added

---

src/list-item/list-item.css
src/list-item/list-item.mdx

feat(list-item): multi line added

---

package.json
src/sidebar/Sidebar.ts
src/sidebar/sidebar.mdx

algumas melhorias na sidebar
- permite iniciar fechada
- dispara o evento onCollapsed quando clica no botão da seta
- permite controlar o "abrir e fechar" manualmente
- não tem breaking change

feat(sidebar): some improvements

---

package.json
src/bolt-css.css
src/icons/icons.css
src/list-item/list-item.css

- adicionado os códigos dos ícones em variáveis podendo ser reutilizado em vários casos
- corrigido hard code do List Item para a variavel do icone

feat(icons): variables

---

package.json
src/input/Input.ts
src/input/input.css
src/input/input.mdx

feat(input): readonly input mode

---

src/bolt-css.css
src/divider/divider.css
src/divider/divider.mdx

feat(divider): divider added

---

package.json
src/bolt-css.css
src/day/Day.ts
src/day/day.css
src/day/day.mdx
src/index.ts
yarn.lock

- tests
-  complete documentation

feat(day): day element added

---

src/icons/icons.css

fix(icons): money icon

---

package.json
src/topbar/Topbar.ts
src/topbar/topbar.mdx

feat(topbar): add currency indicator

---

package.json
src/day/day.css
src/day/day.mdx

fix(day): layout adjustment

---

package.json
src/list-item/list-item.css
src/list-item/list-item.mdx

feat(list-item): secondary colors

---

package.json
src/topbar/Topbar.ts
src/topbar/topbar.css
src/topbar/topbar.mdx

Foi reformulado a forma de exibição da imagem ou icone, agora é possivel exibir uma imagem com url externa. tambem foi tirado a tag de img e adicionado como background.
TESTS
**_-_**
**_-_**
**_-_**
**_-_**
**_-_**
**_-_**
I18N
**_-_**
MULTICURRENCY
**_-_**

fix: fix(topbar): Fixing topbar icon url and shape

---

package.json
src/input/Input.ts
src/input/input.css
src/input/input.mdx
src/menu/Menu.ts

- Faltam os testes de interface

Improving tooltip behavior and fix menu

---

package.json
src/bolt-css.css
src/index.ts
src/station/Station.ts
src/station/station.css
src/station/station.mdx

- complete documentation
- tests

feat(station): station component added
